Style/Documentation:
  Enabled: false

AllCops:
    Exclude:
        - db/**/**
        - config/**/*
        - lib/**/*
        - bin/**/*
        - spec/rails_helper.rb
        - spec/spec_helper.rb
        - vendor/**/*
        - tmp/**/*

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude: 
    - spec/**/*

Layout/LineLength:
  Max: 130
  Exclude:
    - app/models/constants/*